# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16NmGMWf_6p3Ep4GT7Q5SPCNKuemur5YC
"""

class Kitob:
    def __init__(self, nomi, muallif):
        self.nomi = nomi
        self.muallif = muallif

    def __str__(self):
        return f"\"{self.nomi}\" by {self.muallif}"
class Kutubxona:
    def __init__(self):
        self.kitoblar = []

    def kitob_qoshish(self, kitob):
        self.kitoblar.append(kitob)
        print(f"Kitob qo'shildi: {kitob}")

    def kitoblar_royxati(self):
        print("\nKutubxonadagi kitoblar:")
        for kitob in self.kitoblar:
            print(f"- {kitob}")
def kutubxona_tizimi():
    kutubxona = Kutubxona()
    kutubxona.kitob_qoshish(Kitob("Alkimyogar", "Paulo Coelho"))
    kutubxona.kitob_qoshish(Kitob("1984", "George Orwell"))
    kutubxona.kitob_qoshish(Kitob("Sherlock Holmes", "Arthur Conan Doyle"))
    kutubxona.kitoblar_royxati()
if __name__ == "__main__":
    kutubxona_tizimi()